### ISSUE TITLE
[ENHANCEMENT] react-formio@1.x should support React v16

### ISSUE THREAD

**Issue by akaustav** [formio/react#234]
## Environment

- **react-formio branch/tag:**
  - [x] 1.x
- NodeJS version: v12.7.0
- npm version: 6.10.0

## Steps to Reproduce

1. Create/open a React project which uses `react@16.*`
2. Install `formio@1x` as a production dependency on that project.
3. Compile/transpile and execute that React project inside a browser.

## Expected behavior

The project should be able to execute successfully inside a browser without any errors.

## Observed behavior

The project fails to execute. Following error shows on the browser console:

```console
./node_modules/react-formio/lib/components/FormComponents/address.js
Uncaught TypeError: _react2.default.createClass is not a function
```

**Comment by akaustav** [comment]
## More information

Upon further investigations of the error on the browser console, it leads to the fact that react-formio utilizes React.createClass() method at several places (38 instances to be exact). React.createClass() was [deprecated](https://reactjs.org/blog/2017/06/13/react-v15.6.0.html#react) in React v15.5.0 (deprecation warning added in React v15.6.0) in favor of ES6 classes. This method was extracted out into another node module named `create-react-class` and completely removed in React v16.0.0.

From this [blog post](https://reactjs.org/blog/2017/04/07/react-v15.5.0.html#migrating-from-reactcreateclass), I gather that there is a [class codemod](https://github.com/reactjs/react-codemod#explanation-of-the-new-es2015-class-transform-with-property-initializers) which may be able to help migrate into React v16.

I will attempt to execute the codemod and see if I run into any issues.

**Comment by randallknutson** [comment]
Hi Ameet,

I attempted this a while ago and it was quite a bit of work. If you want to work on it you can submit a pull request here and I'll merge it. 

Randall

**Comment by randallknutson** [comment]
I see the pull request. I'll get some builds with the changes here shortly.

**Comment by randallknutson** [comment]
https://github.com/formio/react-formio/pull/235

**Comment by akaustav** [comment]
Thanks, @randallknutson. I raised PR #235 for fixing this specific issue. I have the steps which I took on that ticket too. Although, there is a broken test when I run `npm test`. I am not sure if the test on the 1.x branch was broken prior to my fix. I ran `npm test` in the current 1.x branch. Looks like there is a failure there too - not sure if it's the same failure.

Do you mind confirming that my PR didn't cause the test to fail?

**Comment by akaustav** [comment]
@randallknutson Looks like the `npm test` script runs mocha tests against all `*.spec.js` in all folders (`**/*.spec.js`). This seems to include the `.spec.js` files in the `node_modules` folder too (atleast in Windows - not sure about the behavior in macOS).

For example, the following `.spec.js` files are being picked up for testing:

```console
react-formio\node_modules\text-mask-addons\test\addonsBundle.spec.js:1
react-formio\node_modules\formiojs\node_modules\text-mask-addons\test\addonsBundle.spec.js:1
```

Most of the tests in the 1.x branch lives inside the `src` and `test` folders. So, in my opinion, the `test` script in package.json should read:

```diff
- "test": "mocha --timeout 30000 --reporter spec test/.setup.js **/*.spec.js",
+ "test": "mocha --timeout 30000 --reporter spec test/.setup.js src/**/*.spec.js test/**/*.spec.js",
```

I can try doing that in PR #235 or make another PR for fixing this line.

**Comment by randallknutson** [comment]
This pr is fine

**Comment by akaustav** [comment]
@randallknutson I have limited the `test` script to work on `src` and `test` folders only. Ran tests before and after my PR #235. There are failures in both cases - both failures different from each other.

Here are the results. Before my PR:

```console
D:\GitHub\formio\react-formio>npm test

> react-formio@1.5.25 test D:\GitHub\formio\react-formio
> mocha --timeout 30000 --reporter spec test/.setup.js src/**/*.spec.js test/**/*.spec.js

internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module 'react-widgets/lib/DropdownList'
Require stack:
- D:\GitHub\formio\react-formio\src\components\FormComponents\mixins\selectMixin.jsx
- D:\GitHub\formio\react-formio\src\components\FormComponents\address.jsx
- D:\GitHub\formio\react-formio\src\components\FormComponents\address.spec.js
- D:\GitHub\formio\react-formio\node_modules\mocha\lib\mocha.js
- D:\GitHub\formio\react-formio\node_modules\mocha\index.js
- D:\GitHub\formio\react-formio\node_modules\mocha\bin\_mocha
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (D:/GitHub/formio/react-formio/src/components/FormComponents/mixins/selectMixin.jsx:2:1)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at loader (D:\GitHub\formio\react-formio\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.<computed> [as .jsx] (D:\GitHub\formio\react-formio\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (D:/GitHub/formio/react-formio/src/components/FormComponents/address.jsx:3:1)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at loader (D:\GitHub\formio\react-formio\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.<computed> [as .jsx] (D:\GitHub\formio\react-formio\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (D:/GitHub/formio/react-formio/src/components/FormComponents/address.spec.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at loader (D:\GitHub\formio\react-formio\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.<computed> [as .js] (D:\GitHub\formio\react-formio\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at D:\GitHub\formio\react-formio\node_modules\mocha\lib\mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (D:\GitHub\formio\react-formio\node_modules\mocha\lib\mocha.js:247:14)
    at Mocha.run (D:\GitHub\formio\react-formio\node_modules\mocha\lib\mocha.js:576:10)
    at Object.<anonymous> (D:\GitHub\formio\react-formio\node_modules\mocha\bin\_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\GitHub\\formio\\react-formio\\src\\components\\FormComponents\\mixins\\selectMixin.jsx',
    'D:\\GitHub\\formio\\react-formio\\src\\components\\FormComponents\\address.jsx',
    'D:\\GitHub\\formio\\react-formio\\src\\components\\FormComponents\\address.spec.js',
    'D:\\GitHub\\formio\\react-formio\\node_modules\\mocha\\lib\\mocha.js',
    'D:\\GitHub\\formio\\react-formio\\node_modules\\mocha\\index.js',
    'D:\\GitHub\\formio\\react-formio\\node_modules\\mocha\\bin\\_mocha'
  ]
}
npm ERR! Test failed.  See above for more details.
```

After my PR:

```console
D:\GitHub\akaustav\react-formio>npm test

> react-formio@1.5.25 test D:\GitHub\akaustav\react-formio
> mocha --timeout 30000 --reporter spec test/.setup.js src/**/*.spec.js test/**/*.spec.js

Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.
D:\GitHub\akaustav\react-formio\node_modules\formiojs\lib\formio.js:1368
Formio.Headers = Headers;
                 ^

ReferenceError: Headers is not defined
    at Object.<anonymous> (D:\GitHub\akaustav\react-formio\node_modules\formiojs\lib\formio.js:1368:18)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Object.require.extensions.<computed> [as .js] (D:\GitHub\akaustav\react-formio\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (D:\GitHub\akaustav\react-formio\node_modules\formiojs\lib\formio.form.js:23:15)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Object.require.extensions.<computed> [as .js] (D:\GitHub\akaustav\react-formio\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (D:\GitHub\akaustav\react-formio\node_modules\formiojs\lib\index.js:8:15)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Object.require.extensions.<computed> [as .js] (D:\GitHub\akaustav\react-formio\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (D:/GitHub/akaustav/react-formio/src/components/Formio.jsx:3:1)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at loader (D:\GitHub\akaustav\react-formio\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.<computed> [as .jsx] (D:\GitHub\akaustav\react-formio\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (D:\GitHub\akaustav\react-formio\src\components\index.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at loader (D:\GitHub\akaustav\react-formio\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.<computed> [as .js] (D:\GitHub\akaustav\react-formio\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (D:/GitHub/akaustav/react-formio/src/components/FormComponents/columns.jsx:2:1)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at loader (D:\GitHub\akaustav\react-formio\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.<computed> [as .jsx] (D:\GitHub\akaustav\react-formio\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (D:/GitHub/akaustav/react-formio/src/components/FormComponents/columns.spec.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at loader (D:\GitHub\akaustav\react-formio\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.<computed> [as .js] (D:\GitHub\akaustav\react-formio\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at D:\GitHub\akaustav\react-formio\node_modules\mocha\lib\mocha.js:220:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (D:\GitHub\akaustav\react-formio\node_modules\mocha\lib\mocha.js:217:14)
    at Mocha.run (D:\GitHub\akaustav\react-formio\node_modules\mocha\lib\mocha.js:469:10)
    at Object.<anonymous> (D:\GitHub\akaustav\react-formio\node_modules\mocha\bin\_mocha:404:18)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)
    at internal/main/run_main_module.js:17:11
npm ERR! Test failed.  See above for more details.
```

**Comment by randallknutson** [comment]
Thanks. That is an issue with Headers being a web global object but not in node. We need to add the web context to the tests so that it knows about it. I can fix that.

**Comment by akaustav** [comment]
Thanks, Randall. I noticed that this error seems to be originating from a dependency - formiojs. Specifically the 2.x branch of formiojs. Are you planning on fixing it there?

**Comment by egorkaru** [comment]
Hi @randallknutson, can you review my pr #247 ?

**Comment by randallknutson** [comment]
I'll get this merged the next time I do a build.

**Comment by egorkaru** [comment]
Hi @randallknutson, so it's like about month passed away, can you share next build date? `react-formio@1` it's really one of important part of my project, and switching to newer react version is impossible without this patch:(

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there are no new comments here. I hope it was resolved. If not, please reopen it. Thanks!
