### ISSUE TITLE
With Next.js Got error: document is not defined

### ISSUE THREAD

**Issue by vivekvt** [formio/react#335]
I am getting error for FormBuilder Component. 
I saw old issue from octomber 2019 which is closed https://github.com/formio/react-formio/issues/253 which told react-formio@4 will have SSR Support.
I am got same error in react-formio@4.3.0
document is not defined
```
ReferenceError: document is not defined
    at Object.<anonymous> (/home/vivekvt/Desktop/codemarket.io/unita/files/node_modules/dragula/dist/dragula.js:869:23)
    at Object.8 (/home/vivekvt/Desktop/codemarket.io/unita/files/node_modules/dragula/dist/dragula.js:895:4)
    at s (/home/vivekvt/Desktop/codemarket.io/unita/files/node_modules/dragula/dist/dragula.js:1:621)
    at /home/vivekvt/Desktop/codemarket.io/unita/files/node_modules/dragula/dist/dragula.js:1:672
    at Object.<anonymous> (/home/vivekvt/Desktop/codemarket.io/unita/files/node_modules/dragula/dist/dragula.js:724:19)
    at Object.6../eventmap (/home/vivekvt/Desktop/codemarket.io/unita/files/node_modules/dragula/dist/dragula.js:824:4)
    at s (/home/vivekvt/Desktop/codemarket.io/unita/files/node_modules/dragula/dist/dragula.js:1:621)
    at /home/vivekvt/Desktop/codemarket.io/unita/files/node_modules/dragula/dist/dragula.js:1:672
    at Object.<anonymous> (/home/vivekvt/Desktop/codemarket.io/unita/files/node_modules/dragula/dist/dragula.js:41:17)
    at Object.2../classes (/home/vivekvt/Desktop/codemarket.io/unita/files/node_modules/dragula/dist/dragula.js:647:4)
    at s (/home/vivekvt/Desktop/codemarket.io/unita/files/node_modules/dragula/dist/dragula.js:1:621)
    at e (/home/vivekvt/Desktop/codemarket.io/unita/files/node_modules/dragula/dist/dragula.js:1:792)
    at /home/vivekvt/Desktop/codemarket.io/unita/files/node_modules/dragula/dist/dragula.js:1:810
    at /home/vivekvt/Desktop/codemarket.io/unita/files/node_modules/dragula/dist/dragula.js:1:88
    at Object.<anonymous> (/home/vivekvt/Desktop/codemarket.io/unita/files/node_modules/dragula/dist/dragula.js:1:323)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
```
![Screenshot from 2020-09-23 20-53-46](https://user-images.githubusercontent.com/50275510/94033934-116b4b00-fddf-11ea-8775-c104f0526201.png)

- Hosting type
  -  Local deployment
- Frontend framework: Next.js 9.3.2
 react-formio@4.3.0
- Browser: Google Chrome
- Browser version: 84.0.4147.125

**Comment by TanyaGashtold** [comment]
I am closing the issue as it was created too long ago and there is no new comments here. If the issue is not resolved, please reopen it. Thanks!

**Comment by umarq91** [comment]
This is still not resolved. Can we reopen this? I am using Next and getting this error constantly:

Next: 15.1.5
React: 18.3.1

**Comment by lane-formio** [comment]
Are you using @formio/react@6.0.0?

**Comment by lane-formio** [comment]
<div>Agent Tatsiana Ivashevich linked Freshdesk ticket <a href="https://formhelp.freshdesk.com/a/tickets/54872">54872</a> for this issue.</div><br/>

**Comment by umarq91** [comment]
Yes its 6.0.0

**Comment by brendanbond** [comment]
@umarq91 did you see https://github.com/formio/react?tab=readme-ov-file#usage-in-nextjs ?
